### PR TITLE
Save/Load Level feature

### PR DESCRIPTION
**Pull request by dershao**

### CODE REVIEW

**Comment by DwangDistracted** [comment]
The Load Menu is still throwing IllegalArgumentException when there is no saved directory

**Comment by DwangDistracted** [comment]
image

**Comment by dershao** [comment]
I don't get the errors you're describing.

**Comment by DwangDistracted** [comment]
> 
> 
> I don't get the errors you're describing.

Yeah that was my bad. I forgot to refresh my eclipse

**Comment by dershao** [comment]
👌

**Pull request merged**
